---
name: build and test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk-23
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: temurin
          cache: maven
      - name: execute maven
        run: ./mvnw -B verify
